"""
Streetlight data processing script — Hopkins Street Safety Data Story

Processes Streetlight exports from data/raw/streetlight/ and produces
cleaned, analysis-ready files in data/processed/.

FILE STRUCTURE (actual, confirmed from raw data audit):
  Vehicles:   2012902_Hopkins_Rose_Cedar_AV_2025/
                *_network_performance_seg_metrics.csv  (segment-based, 2025)
                *_network_performance_seg_prediction_interval.csv
  Pedestrian: 2013191_Hopkins_Rose_Cedar_Ped/
                *_za_ped.csv  (zone activity, 2022)
  Bicycle:    2013334_Hopkins_Rose_Cedar_Bike/
                *_za_bike.csv  (zone activity, 2022)

All three modes use StL Volume (confirmed). Cross-mode comparison is valid
in terms of unit type, but structural difference must be noted in all UI:
  - Vehicles: segment-based network performance metrics
  - Ped/bike: zone-based activity metrics

Run from repo root:
  python analysis/streetlight.py

Data integrity: every output value traces directly to a source CSV.
"""

import sys
import json
from datetime import datetime
from pathlib import Path

import pandas as pd

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

REPO_ROOT     = Path(__file__).resolve().parent.parent
RAW_DIR       = REPO_ROOT / "data" / "raw" / "streetlight"
PROCESSED_DIR = REPO_ROOT / "data" / "processed"

OUTPUT_VEHICLES_NP    = PROCESSED_DIR / "vehicles_network_performance.csv"
OUTPUT_ZA_PEDESTRIANS = PROCESSED_DIR / "za_pedestrians.csv"
OUTPUT_ZA_BICYCLES    = PROCESSED_DIR / "za_bicycles.csv"
OUTPUT_PREDICTION     = PROCESSED_DIR / "vehicle_prediction_intervals.csv"
OUTPUT_VERIFIED_JSON  = PROCESSED_DIR / "streetlight_verified.json"
OUTPUT_SUMMARY_JSON   = PROCESSED_DIR / "streetlight_summary.json"
INTEGRITY_NOTES       = PROCESSED_DIR / "data_integrity_notes.md"

PROCESSED_DIR.mkdir(parents=True, exist_ok=True)


# ---------------------------------------------------------------------------
# Utility
# ---------------------------------------------------------------------------

def _safe_col(df, candidates):
    """Return the first column name from candidates that exists in df."""
    for c in candidates:
        if c in df.columns:
            return c
    cl = df.columns.str.lower()
    for c in candidates:
        matches = df.columns[cl == c.lower()].tolist()
        if matches:
            return matches[0]
    return None


def _append_integrity_note(text):
    INTEGRITY_NOTES.parent.mkdir(parents=True, exist_ok=True)
    with open(INTEGRITY_NOTES, "a") as f:
        f.write(f"\n---\n\n*Generated by analysis/streetlight.py on "
                f"{datetime.utcnow().isoformat()}Z*\n\n")
        f.write(text)
        f.write("\n")


# ---------------------------------------------------------------------------
# STEP 1 — Full file audit
# ---------------------------------------------------------------------------

def audit_files():
    """Walk data/raw/streetlight/ and print a complete audit of every CSV."""
    print("\n" + "=" * 70)
    print("STEP 1 — FULL FILE AUDIT")
    print("=" * 70)

    csv_files = sorted(RAW_DIR.rglob("*.csv"))
    if not csv_files:
        print(f"\n[ERROR] No CSV files found in {RAW_DIR}")
        sys.exit(1)

    audit = {}

    for fpath in csv_files:
        rel = fpath.relative_to(REPO_ROOT)
        size_kb = fpath.stat().st_size / 1024
        print(f"\n{'─'*60}")
        print(f"FILE: {rel}  ({size_kb:.1f} KB)")

        df = pd.read_csv(fpath, low_memory=False)
        cols = list(df.columns)
        print(f"  Rows: {len(df)}")
        print(f"  Columns: {cols}")

        mode_col     = next((c for c in cols if "mode" in c.lower()), None)
        daytype_col  = next((c for c in cols if "day type" in c.lower()), None)
        daypart_col  = next((c for c in cols if "day part" in c.lower()), None)
        period_col   = next((c for c in cols if "data period" in c.lower()), None)

        modes     = sorted(df[mode_col].dropna().unique().tolist())     if mode_col    else []
        day_types = sorted(df[daytype_col].dropna().unique().tolist())  if daytype_col else []
        day_parts = sorted(df[daypart_col].dropna().unique().tolist())  if daypart_col else []

        print(f"  Mode: {modes}")
        print(f"  Day Types: {day_types}")
        print(f"  Day Parts: {day_parts}")

        # Detect metric column and unit type
        metric_col  = None
        metric_type = None
        for c in cols:
            cl = c.lower()
            if "stl volume" in cl or "average daily" in cl or "segment traffic" in cl:
                metric_col  = c
                metric_type = "StL Volume"
                break
        if metric_col is None:
            for c in cols:
                cl = c.lower()
                if "calibrated index" in cl:
                    metric_col  = c
                    metric_type = "StreetLight Calibrated Index"
                    break
                elif "index" in cl and "streetlight" in cl:
                    metric_col  = c
                    metric_type = "StreetLight Index"
                    break

        print(f"  Primary metric: {metric_col!r}  →  {metric_type}")

        if period_col:
            vals = df[period_col].dropna().astype(str)
            print(f"  Data period: {vals.min()} → {vals.max()}")

        if metric_type and "Index" in metric_type:
            print("  ⚠️  WARNING: Index unit — cannot compare with Volume modes")

        audit[str(fpath)] = {
            "path": str(rel), "size_kb": round(size_kb, 1),
            "row_count": len(df), "columns": cols,
            "metric_col": metric_col, "metric_type": metric_type,
        }

    return audit


# ---------------------------------------------------------------------------
# STEP 2 — Process zone activity: pedestrian and bicycle only
# ---------------------------------------------------------------------------

def process_zone_activity():
    """
    Read *_za_ped.csv and *_za_bike.csv. Vehicles do NOT have zone activity
    files — vehicle data comes from network performance (Step 4).

    Saves:
      data/processed/za_pedestrians.csv
      data/processed/za_bicycles.csv

    Returns dict: {mode_key: (dataframe, output_unit_col)}
    """
    print("\n" + "=" * 70)
    print("STEP 2 — PROCESS ZONE ACTIVITY (pedestrian + bicycle)")
    print("=" * 70)
    print("  NOTE: No zone activity file for vehicles — vehicle volumes come")
    print("        from network performance segment metrics (Step 4).")

    results = {}

    targets = [
        ("*_za_ped.csv",  "pedestrians", OUTPUT_ZA_PEDESTRIANS),
        ("*_za_bike.csv", "bicycles",    OUTPUT_ZA_BICYCLES),
    ]

    for glob_pattern, mode_key, out_path in targets:
        files = sorted(RAW_DIR.rglob(glob_pattern))
        if not files:
            print(f"\n  [SKIP] No files matching {glob_pattern}")
            continue

        frames = []
        for fpath in files:
            df = pd.read_csv(fpath, low_memory=False)
            frames.append(df)
            print(f"\n  Loaded ({mode_key}): {fpath.name}  ({len(df)} rows)")

        combined = pd.concat(frames, ignore_index=True)

        zone_id_col   = _safe_col(combined, ["Zone ID", "zone_id"])
        zone_name_col = _safe_col(combined, ["Zone Name", "zone_name"])
        mode_col      = _safe_col(combined, ["Mode of Travel", "Mode"])
        daytype_col   = _safe_col(combined, ["Day Type", "day_type"])
        daypart_col   = _safe_col(combined, ["Day Part", "day_part"])
        period_col    = _safe_col(combined, ["Data Periods", "data_periods"])

        # Zone traffic column — should be "Average Daily Zone Traffic (StL Volume)"
        metric_col = None
        for c in combined.columns:
            if "average daily zone traffic" in c.lower() or "zone traffic" in c.lower():
                metric_col = c
                break

        missing = [n for n, v in [
            ("Zone ID", zone_id_col), ("Zone Name", zone_name_col),
            ("Mode of Travel", mode_col), ("Day Type", daytype_col),
            ("Day Part", daypart_col), ("Zone Traffic", metric_col),
        ] if v is None]
        if missing:
            print(f"  [ERROR] Missing columns for {mode_key}: {missing}")
            print(f"  Available: {list(combined.columns)}")
            sys.exit(1)

        df_out = combined[[
            zone_id_col, zone_name_col, mode_col,
            daytype_col, daypart_col, metric_col
        ]].copy()
        if period_col:
            df_out.insert(0, "data_periods", combined[period_col])

        df_out.columns = (
            (["data_periods"] if period_col else []) +
            ["zone_id", "zone_name", "mode_of_travel",
             "day_type", "day_part", "zone_traffic"]
        )
        df_out["output_unit"] = metric_col

        df_out.to_csv(out_path, index=False)
        print(f"  ✓ {mode_key}: {len(df_out)} rows → {out_path.relative_to(REPO_ROOT)}")
        print(f"    Output unit: {metric_col!r}")

        zones = sorted(df_out["zone_name"].dropna().unique().tolist())
        print(f"    Zones: {zones}")

        results[mode_key] = (df_out, metric_col)

    return results


# ---------------------------------------------------------------------------
# STEP 3 — Process prediction intervals (vehicles only)
# ---------------------------------------------------------------------------

def process_prediction_intervals():
    """
    Read *_prediction_interval*.csv (vehicle confidence intervals).
    Saves to data/processed/vehicle_prediction_intervals.csv.
    """
    print("\n" + "=" * 70)
    print("STEP 3 — PROCESS PREDICTION INTERVALS (vehicles)")
    print("=" * 70)

    # Filename: *_network_performance_seg_prediction_interval.csv (no trailing 's')
    pi_files = sorted(RAW_DIR.rglob("*_prediction_interval*.csv"))
    # Exclude monthly files for the primary output
    pi_files = [f for f in pi_files if "monthly" not in f.name.lower()]

    if not pi_files:
        print("  [SKIP] No prediction interval files found.")
        return None

    frames = []
    for fpath in pi_files:
        df = pd.read_csv(fpath, low_memory=False)
        frames.append(df)
        print(f"  Loaded: {fpath.name}  ({len(df)} rows)")
        print(f"  Columns: {list(df.columns)}")

    combined = pd.concat(frames, ignore_index=True)

    zone_id_col   = _safe_col(combined, ["Zone ID", "zone_id"])
    zone_name_col = _safe_col(combined, ["Zone Name", "zone_name"])
    period_col    = _safe_col(combined, ["Year/Month", "Data Periods", "data_periods"])

    vol_col = None
    for c in combined.columns:
        if "average daily" in c.lower() and ("volume" in c.lower() or "traffic" in c.lower()):
            vol_col = c
            break

    lower_col = upper_col = None
    for c in combined.columns:
        cl = c.lower()
        if "lower" in cl:
            lower_col = c
        elif "upper" in cl:
            upper_col = c

    print(f"  Volume column:  {vol_col!r}")
    print(f"  Lower 95% CI:   {lower_col!r}")
    print(f"  Upper 95% CI:   {upper_col!r}")

    col_map = {
        k: v for k, v in {
            zone_id_col:   "zone_id",
            zone_name_col: "zone_name",
            period_col:    "year_month",
            vol_col:       "avg_daily_volume",
            lower_col:     "lower_95",
            upper_col:     "upper_95",
        }.items() if k is not None
    }
    df_out = combined[list(col_map.keys())].rename(columns=col_map)
    df_out.to_csv(OUTPUT_PREDICTION, index=False)
    print(f"  ✓ {len(df_out)} rows → {OUTPUT_PREDICTION.relative_to(REPO_ROOT)}")
    return df_out


# ---------------------------------------------------------------------------
# STEP 4 — Process network performance: vehicle segments (speed + volume)
# ---------------------------------------------------------------------------

def process_network_performance():
    """
    Read *_network_performance_seg_metrics*.csv — this is the primary vehicle
    volume AND speed data source. (No za_ file exists for vehicles.)

    Saves to data/processed/vehicles_network_performance.csv.
    """
    print("\n" + "=" * 70)
    print("STEP 4 — PROCESS NETWORK PERFORMANCE (vehicle segments)")
    print("=" * 70)

    # Pattern: *_network_performance_seg_metrics.csv (no trailing wildcard segment)
    np_files = sorted(RAW_DIR.rglob("*_network_performance_seg_metrics*.csv"))
    # Exclude monthly files for the primary output
    np_files = [f for f in np_files if "monthly" not in f.name.lower()]

    if not np_files:
        print("  [SKIP] No network performance segment metrics files found.")
        return None, {}, []

    frames = []
    for fpath in np_files:
        df = pd.read_csv(fpath, low_memory=False)
        frames.append(df)
        print(f"  Loaded: {fpath.name}  ({len(df)} rows)")

    combined = pd.concat(frames, ignore_index=True)
    print(f"  All columns: {list(combined.columns)}")

    zone_id_col       = _safe_col(combined, ["Zone ID", "zone_id"])
    zone_name_col     = _safe_col(combined, ["Zone Name", "zone_name"])
    daytype_col       = _safe_col(combined, ["Day Type", "day_type"])
    daypart_col       = _safe_col(combined, ["Day Part", "day_part"])
    period_col        = _safe_col(combined, ["Data Periods", "data_periods"])
    inferred_col      = _safe_col(combined, ["Inferred Volume", "inferred_volume"])

    # Volume: "Average Daily Segment Traffic (StL Volume)"
    seg_traffic_col = None
    for c in combined.columns:
        if "segment traffic" in c.lower() and "average" in c.lower():
            seg_traffic_col = c
            break
        elif "segment traffic" in c.lower():
            seg_traffic_col = c

    # Speed columns — exact names from actual file
    avg_speed_col     = _safe_col(combined, ["Avg Segment Speed (mph)", "Avg Speed (mph)"])
    free_flow_col     = _safe_col(combined, ["Free Flow Speed (mph)"])
    free_flow_fac_col = _safe_col(combined, ["Free Flow Factor"])

    # Speed percentiles — look for "Nth Speed Percentile" pattern
    # Must match each percentile to its own column, not the first match found
    pct_cols = {}
    for pct in [5, 15, 85, 95]:
        for c in combined.columns:
            cl = c.lower()
            if f"{pct}th speed percentile" in cl or f"{pct}th percentile" in cl:
                pct_cols[pct] = c
                break

    print(f"  Segment traffic:   {seg_traffic_col!r}")
    print(f"  Avg speed:         {avg_speed_col!r}")
    print(f"  Free flow speed:   {free_flow_col!r}")
    print(f"  Free flow factor:  {free_flow_fac_col!r}")
    print(f"  Inferred volume:   {inferred_col!r}")
    print(f"  Speed percentiles: {pct_cols}")

    select_map = {k: v for k, v in {
        zone_id_col:       "zone_id",
        zone_name_col:     "zone_name",
        period_col:        "data_periods",
        daytype_col:       "day_type",
        daypart_col:       "day_part",
        seg_traffic_col:   "segment_traffic",
        avg_speed_col:     "avg_speed_mph",
        free_flow_col:     "free_flow_speed_mph",
        free_flow_fac_col: "free_flow_factor",
        inferred_col:      "inferred_volume",
    }.items() if k is not None}
    for pct, col in pct_cols.items():
        select_map[col] = f"speed_p{pct}"

    df_out = combined[list(select_map.keys())].rename(columns=select_map)
    df_out.to_csv(OUTPUT_VEHICLES_NP, index=False)
    print(f"  ✓ {len(df_out)} rows → {OUTPUT_VEHICLES_NP.relative_to(REPO_ROOT)}")

    zones = sorted(df_out["zone_name"].dropna().unique().tolist())
    print(f"  Zones/segments: {zones}")

    if "speed_p85" in df_out.columns:
        print("\n  ★ speed_p85 = 85th percentile — California CVC §22358.5 standard")

    inferred_zones = []
    if "inferred_volume" in df_out.columns:
        inferred_zones = df_out[
            df_out["inferred_volume"].astype(str).str.lower().isin(["yes", "true", "1", "y"])
        ]["zone_name"].unique().tolist()
        if inferred_zones:
            print(f"\n  ⚠️  INFERRED VOLUME ZONES: {inferred_zones}")

    return df_out, pct_cols, inferred_zones


# ---------------------------------------------------------------------------
# STEP 5 — Build streetlight_verified.json
# ---------------------------------------------------------------------------

def build_verified_json(za_results, df_prediction, df_network, pct_cols, inferred_zones):
    """Build data/processed/streetlight_verified.json from processed data."""
    print("\n" + "=" * 70)
    print("STEP 5 — BUILD streetlight_verified.json")
    print("=" * 70)

    ped_unit  = za_results.get("pedestrians", (None, None))[1] or "not present"
    bike_unit = za_results.get("bicycles",    (None, None))[1] or "not present"

    # Derive vehicle period from network performance data
    vehicle_period = "Jan 01 2025 - Dec 31 2025"
    if df_network is not None and "data_periods" in df_network.columns:
        vals = df_network["data_periods"].dropna().astype(str)
        if len(vals):
            vehicle_period = vals.iloc[0]

    # Derive ped/bike periods from za data
    def _get_period(df):
        if df is None:
            return "unknown"
        if "data_periods" in df.columns:
            vals = df["data_periods"].dropna().astype(str)
            return vals.iloc[0] if len(vals) else "unknown"
        return "Jan 01 2022 - Aug 31 2022"

    ped_df   = za_results.get("pedestrians", (None,))[0]
    bike_df  = za_results.get("bicycles",    (None,))[0]
    ped_period  = _get_period(ped_df)
    bike_period = _get_period(bike_df)

    zones = []
    if df_network is not None and "zone_name" in df_network.columns:
        zones = sorted(df_network["zone_name"].dropna().unique().tolist())

    metadata = {
        "status": "VERIFIED",
        "generated": datetime.utcnow().isoformat() + "Z",
        "analysis_ids": {
            "vehicles": "2012902 — Hopkins Rose Cedar AV 2025",
            "pedestrians": "2013191 — Hopkins Rose Cedar Ped",
            "bicycles": "2013334 — Hopkins Rose Cedar Bike",
        },
        "output_units": {
            "vehicles": "Average Daily Segment Traffic (StL Volume) — from network performance",
            "pedestrians": ped_unit,
            "bicycles": bike_unit,
        },
        "vehicle_file_type": "network_performance_seg_metrics",
        "ped_bike_file_type": "zone_activity",
        "structural_note": (
            "Vehicle volumes are segment-based (network performance); "
            "ped/bike volumes are zone-based (zone activity). Both use StL Volume. "
            "Segment and zone boundaries roughly correspond but are not identical — "
            "do not treat as precisely equivalent geographic units."
        ),
        "modes_comparable": True,
        "comparability_note": (
            "All modes use StL Volume. Cross-mode comparison is valid in unit terms. "
            "However, vehicle data uses segment metrics and ped/bike use zone activity — "
            "this structural difference must be disclosed in any UI showing modes together."
        ),
        "data_periods": {
            "vehicles": vehicle_period,
            "pedestrians": ped_period,
            "bicycles": bike_period,
        },
        "day_parts_available": [
            "All Day", "Early AM", "Peak AM", "Mid-Day", "Peak PM", "Late PM"
        ],
        "day_types_available": ["All Days", "Weekday", "Weekend"],
        "speed_percentiles_available": sorted(list(pct_cols.keys())) if pct_cols else [],
        "zones": zones,
        "confidence_intervals_available": df_prediction is not None,
        "inferred_volume_zones": inferred_zones,
        "notes": (
            "Verified against raw Streetlight CSV exports. "
            + (f"Inferred volume zones: {inferred_zones}. " if inferred_zones else "")
        ),
    }

    # --- zone_activity (ped + bike) ---
    zone_activity = {}
    for mode_key, (df, unit) in za_results.items():
        if df is None:
            continue
        mode_data = {}
        for _, row in df.iterrows():
            zone = str(row.get("zone_name", ""))
            dt   = str(row.get("day_type", ""))
            dp   = str(row.get("day_part", ""))
            val  = row.get("zone_traffic")
            if zone not in mode_data:
                mode_data[zone] = {}
            mode_data[zone][f"{dt} / {dp}"] = val
        zone_activity[mode_key] = mode_data

    # --- prediction_intervals ---
    prediction_intervals = {}
    if df_prediction is not None:
        for _, row in df_prediction.iterrows():
            zone = str(row.get("zone_name", ""))
            ym   = str(row.get("year_month", ""))
            prediction_intervals.setdefault(zone, {})[ym] = {
                "avg_daily_volume": row.get("avg_daily_volume"),
                "lower_95":         row.get("lower_95"),
                "upper_95":         row.get("upper_95"),
            }

    # --- network_performance (vehicles) ---
    network_performance = {}
    if df_network is not None:
        for _, row in df_network.iterrows():
            zone = str(row.get("zone_name", ""))
            dt   = str(row.get("day_type", ""))
            dp   = str(row.get("day_part", ""))
            entry = {
                "segment_traffic":     row.get("segment_traffic"),
                "avg_speed_mph":       row.get("avg_speed_mph"),
                "free_flow_speed_mph": row.get("free_flow_speed_mph"),
                "free_flow_factor":    row.get("free_flow_factor"),
            }
            for pct in [5, 15, 85, 95]:
                key = f"speed_p{pct}"
                if key in df_network.columns:
                    entry[key] = row.get(key)
            if "inferred_volume" in df_network.columns:
                entry["inferred_volume"] = row.get("inferred_volume")
            network_performance.setdefault(zone, {})[f"{dt} / {dp}"] = entry

    verified = {
        "_metadata": metadata,
        "zone_activity": zone_activity,
        "prediction_intervals": prediction_intervals,
        "network_performance": network_performance,
    }

    with open(OUTPUT_VERIFIED_JSON, "w") as f:
        json.dump(verified, f, indent=2, default=str)

    print(f"  ✓ Written: {OUTPUT_VERIFIED_JSON.relative_to(REPO_ROOT)}")
    return verified


# ---------------------------------------------------------------------------
# STEP 6 — Update streetlight_summary.json
# ---------------------------------------------------------------------------

def update_summary_json(verified):
    print("\n" + "=" * 70)
    print("STEP 6 — UPDATE streetlight_summary.json")
    print("=" * 70)

    if not OUTPUT_SUMMARY_JSON.exists():
        print(f"  [SKIP] {OUTPUT_SUMMARY_JSON} does not exist.")
        return

    with open(OUTPUT_SUMMARY_JSON) as f:
        summary = json.load(f)

    corrections = []
    old_status = summary.get("_metadata", {}).get("status", "")
    if "UNVERIFIED" in old_status:
        summary["_metadata"]["status"] = "VERIFIED"
        summary["_metadata"]["verified_at"] = datetime.utcnow().isoformat() + "Z"
        corrections.append({
            "field": "_metadata.status",
            "old_value": old_status,
            "new_value": "VERIFIED",
            "source": "Raw Streetlight CSV exports — see streetlight_verified.json",
        })

    np_data = verified.get("network_performance", {})
    if np_data:
        for zone, periods in np_data.items():
            all_day = periods.get("0: All Days (M-Su) / 0: All Day (12am-12am)", {})
            verified_vol = all_day.get("segment_traffic")
            if verified_vol is None:
                continue
            for seg in summary.get("vehicle_volumes", {}).get("segments", []):
                if seg.get("label", "").lower() in zone.lower():
                    old_vol = seg.get("volume")
                    if old_vol is not None and str(old_vol) != str(verified_vol):
                        seg["volume"] = verified_vol
                        corrections.append({
                            "field": f"vehicle_volumes.segments[{seg.get('id')}].volume",
                            "old_value": old_vol,
                            "new_value": verified_vol,
                            "source": f"network_performance CSV, zone='{zone}'",
                        })

    if corrections:
        summary.setdefault("_metadata", {})["corrections"] = corrections
        print(f"  {len(corrections)} correction(s):")
        for c in corrections:
            print(f"    {c['field']}: {c['old_value']} → {c['new_value']}")
    else:
        print("  No corrections needed.")

    with open(OUTPUT_SUMMARY_JSON, "w") as f:
        json.dump(summary, f, indent=2)
    print(f"  ✓ Updated: {OUTPUT_SUMMARY_JSON.relative_to(REPO_ROOT)}")


# ---------------------------------------------------------------------------
# STEP 7 — Final summary + integrity note
# ---------------------------------------------------------------------------

def print_final_summary(za_results, df_prediction, df_network, pct_cols, inferred_zones, verified):
    print("\n" + "=" * 70)
    print("STEP 7 — FINAL SUMMARY")
    print("=" * 70)

    meta = verified.get("_metadata", {})

    print(f"\n  Segments/zones found:")
    for z in meta.get("zones", []):
        print(f"    - {z}")

    print(f"\n  Modes processed:")
    for mode, unit in meta.get("output_units", {}).items():
        print(f"    - {mode:15s}  unit: {unit}")

    print(f"\n  File types:")
    print(f"    vehicles:  {meta.get('vehicle_file_type')}")
    print(f"    ped/bike:  {meta.get('ped_bike_file_type')}")

    print(f"\n  modes_comparable: {meta.get('modes_comparable')}")
    print(f"  {meta.get('comparability_note', '')}")

    print(f"\n  Confidence intervals: {meta.get('confidence_intervals_available')}")
    print(f"  Speed percentiles:    {meta.get('speed_percentiles_available')}")

    if inferred_zones:
        print(f"\n  ⚠️  Inferred volume zones: {inferred_zones}")

    print(f"\n  Output files:")
    for p in [OUTPUT_VEHICLES_NP, OUTPUT_ZA_PEDESTRIANS, OUTPUT_ZA_BICYCLES,
              OUTPUT_PREDICTION, OUTPUT_VERIFIED_JSON, OUTPUT_SUMMARY_JSON]:
        exists = "✓" if p.exists() else "—"
        print(f"    {exists}  {p.relative_to(REPO_ROOT)}")

    _append_integrity_note(
        "## Vehicle vs Ped/Bike File Structure\n\n"
        "Vehicle volumes come from network performance segment metrics "
        "(`*_network_performance_seg_metrics*.csv`), not zone activity files. "
        "Pedestrian and bicycle volumes come from zone activity files (`*_za_ped.csv`, "
        "`*_za_bike.csv`). All three modes use StL Volume — cross-mode comparison is "
        "valid in unit terms. However, vehicle data is segment-based and ped/bike data "
        "is zone-based. Segment and zone boundaries roughly correspond but are not "
        "identical. This structural difference must be disclosed in any UI element "
        "that displays vehicle and ped/bike volumes together.\n"
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    print("Hopkins Street Safety — Streetlight Data Processing")
    print(f"Source: {RAW_DIR}")
    print(f"Output: {PROCESSED_DIR}")

    if not RAW_DIR.exists():
        print(f"\n[ERROR] {RAW_DIR} does not exist.")
        sys.exit(1)

    audit = audit_files()

    za_results   = process_zone_activity()
    df_prediction = process_prediction_intervals()
    np_result    = process_network_performance()

    if np_result is not None and np_result[0] is not None:
        df_network, pct_cols, inferred_zones = np_result
    else:
        df_network, pct_cols, inferred_zones = None, {}, []

    verified = build_verified_json(za_results, df_prediction, df_network, pct_cols, inferred_zones)
    update_summary_json(verified)
    print_final_summary(za_results, df_prediction, df_network, pct_cols, inferred_zones, verified)

    print("\n✓ Done. Review output files in data/processed/\n")


if __name__ == "__main__":
    main()
