/**
 * CollisionChart.jsx — Prompt 6
 *
 * "The cost of doing nothing" — collision history on the Hopkins corridor.
 *
 * DATA SOURCE:
 *   data/processed/collisions_summary.json
 *   Generated by analysis/collisions.py from TIMS/SWITRS export.
 *   If _metadata.source_status === 'SECONDARY_SOURCE', renders a visible
 *   DATA PENDING banner instead of the bar chart.
 *
 * Props:
 *   data   object — collision summary JSON (defaults to imported file)
 *
 * Attribution: "Source: TIMS/SWITRS" must be visible on every render.
 */

import { useEffect, useRef } from 'react'
import * as d3 from 'd3'
import defaultData from '@data/processed/collisions_summary.json'

// Design tokens
const COLORS = {
  fatal:                     '#8b2c2c',
  severe_injury:             '#a85a2a',
  other_injury:              '#c4713b',
  property_damage:           '#8a9a78',
  grid:                      'rgba(255,255,255,0.08)',
  axis:                      '#8a9a78',
  bracket_bikeEastBay:       'rgba(138,154,120,0.12)',
  bracketStroke_bikeEastBay: 'rgba(138,154,120,0.4)',
  bracket_city:              'rgba(196,113,59,0.15)',
  bracketStroke_city:        'rgba(196,113,59,0.5)',
}

// Four distinct severity stacks — property_damage rendered first (bottom)
const SEVERITY_KEYS = ['property_damage', 'other_injury', 'severe_injury', 'fatal']

export default function CollisionChart({ data = defaultData }) {
  const svgRef = useRef(null)
  const meta = data?._metadata ?? {}
  const isPending = meta.source_status === 'SECONDARY_SOURCE'

  // Big-stat values — pulled directly from JSON, never hardcoded
  const total         = data?.total_collisions ?? null
  const fatals        = data?.fatal_collisions ?? null
  const pedCyclistPct = data?.ped_cyclist_involvement?.pct_of_all_collisions ?? null

  // Date range for subhead — from metadata, not hardcoded
  const dateMin = meta?.date_range?.min ? new Date(meta.date_range.min).getFullYear() : null
  const dateMax = meta?.date_range?.max ? new Date(meta.date_range.max).getFullYear() : null
  const dateRangeLabel = dateMin && dateMax ? `${dateMin}–${dateMax}` : 'full time series'

  // ── D3 bar chart ──────────────────────────────────────────────────────
  useEffect(() => {
    if (isPending) return
    if (!svgRef.current) return

    const byYear = data?.by_year ?? {}
    if (!Object.keys(byYear).length) return

    const containerWidth = svgRef.current.parentElement?.clientWidth ?? 600
    const margin = { top: 30, right: 20, bottom: 32, left: 32 }
    const width  = containerWidth - margin.left - margin.right
    const height = 200 - margin.top - margin.bottom

    const years = Object.keys(byYear).map(Number).sort((a, b) => a - b)

    // by_year values may be plain counts or per-severity objects.
    // Plain counts: stack everything as other_injury (most visible) with no
    // severity breakdown — chart note explains this.
    const hasSeverityBreakdown = typeof Object.values(byYear)[0] === 'object'

    const rows = years.map((yr) => {
      const v = byYear[yr]
      if (hasSeverityBreakdown) {
        return {
          year: yr,
          fatal:           v.fatal             ?? 0,
          severe_injury:   v.severe_injury      ?? 0,
          other_injury:    v.other_injury       ?? 0,
          property_damage: v.property_damage_only ?? v.property_damage ?? 0,
        }
      }
      // Plain count — no per-year severity breakdown available
      return { year: yr, fatal: 0, severe_injury: 0, other_injury: v, property_damage: 0 }
    })

    const series = d3.stack().keys(SEVERITY_KEYS)(rows)

    d3.select(svgRef.current).selectAll('*').remove()

    const svg = d3.select(svgRef.current)
      .attr('width', containerWidth)
      .attr('height', height + margin.top + margin.bottom)
      .attr('role', 'img')
      .attr('aria-label', `Bar chart: ${total ?? ''} collisions on Hopkins corridor by year`)

    const g = svg.append('g')
      .attr('transform', `translate(${margin.left},${margin.top})`)

    const xScale = d3.scaleBand()
      .domain(years)
      .range([0, width])
      .padding(0.25)

    const yMax = d3.max(rows, (d) =>
      d.fatal + d.severe_injury + d.other_injury + d.property_damage,
    ) ?? 10
    const yScale = d3.scaleLinear()
      .domain([0, Math.ceil(yMax * 1.2)])
      .range([height, 0])

    // Gridlines
    g.append('g')
      .call(
        d3.axisLeft(yScale)
          .tickSize(-width)
          .tickFormat('')
          .ticks(4),
      )
      .call((ax) => ax.select('.domain').remove())
      .call((ax) => ax.selectAll('.tick line').attr('stroke', COLORS.grid))

    // ── Annotation 1: 2015–2018, Bike East Bay cited period ────────────
    const bx1 = xScale(2015)
    const bx2 = xScale(2018) != null ? xScale(2018) + xScale.bandwidth() : null
    if (bx1 != null && bx2 != null) {
      g.append('rect')
        .attr('x', bx1).attr('y', 0)
        .attr('width', bx2 - bx1).attr('height', height)
        .attr('fill', COLORS.bracket_bikeEastBay)
        .attr('stroke', COLORS.bracketStroke_bikeEastBay)
        .attr('stroke-width', 1).attr('rx', 2)
      g.append('text')
        .attr('x', bx1 + (bx2 - bx1) / 2).attr('y', -18)
        .attr('text-anchor', 'middle')
        .attr('fill', '#8a9a78')
        .attr('font-family', "'DM Sans', sans-serif")
        .attr('font-size', '9px')
        .text('Bike East Bay cited period')
    }

    // ── Annotation 2: 2016–2019, city workshop cited period ────────────
    const cx1 = xScale(2016)
    const cx2 = xScale(2019) != null ? xScale(2019) + xScale.bandwidth() : null
    if (cx1 != null && cx2 != null) {
      g.append('rect')
        .attr('x', cx1).attr('y', 0)
        .attr('width', cx2 - cx1).attr('height', height)
        .attr('fill', COLORS.bracket_city)
        .attr('stroke', COLORS.bracketStroke_city)
        .attr('stroke-width', 1).attr('rx', 2)
      g.append('text')
        .attr('x', cx1 + (cx2 - cx1) / 2).attr('y', -6)
        .attr('text-anchor', 'middle')
        .attr('fill', '#c4713b')
        .attr('font-family', "'DM Sans', sans-serif")
        .attr('font-size', '9px')
        .text("City's cited period")
    }

    // Stacked bars
    const colorMap = {
      fatal:           COLORS.fatal,
      severe_injury:   COLORS.severe_injury,
      other_injury:    COLORS.other_injury,
      property_damage: COLORS.property_damage,
    }

    g.selectAll('g.series')
      .data(series)
      .join('g')
      .attr('class', 'series')
      .attr('fill', (d) => colorMap[d.key] ?? COLORS.property_damage)
      .selectAll('rect')
      .data((d) => d)
      .join('rect')
      .attr('x', (d) => xScale(d.data.year))
      .attr('y', (d) => yScale(d[1]))
      .attr('height', (d) => Math.max(0, yScale(d[0]) - yScale(d[1])))
      .attr('width', xScale.bandwidth())

    // X axis
    g.append('g')
      .attr('transform', `translate(0,${height})`)
      .call(
        d3.axisBottom(xScale)
          .tickFormat((d) => `'${String(d).slice(-2)}`)
          .tickSize(3),
      )
      .call((ax) => ax.select('.domain').attr('stroke', COLORS.axis))
      .call((ax) =>
        ax.selectAll('.tick text')
          .attr('fill', COLORS.axis)
          .attr('font-family', "'JetBrains Mono', monospace")
          .attr('font-size', '9px'),
      )
      .call((ax) => ax.selectAll('.tick line').attr('stroke', COLORS.axis))

    // Y axis
    g.append('g')
      .call(d3.axisLeft(yScale).ticks(4).tickSize(3))
      .call((ax) => ax.select('.domain').attr('stroke', COLORS.axis))
      .call((ax) =>
        ax.selectAll('.tick text')
          .attr('fill', COLORS.axis)
          .attr('font-family', "'JetBrains Mono', monospace")
          .attr('font-size', '9px'),
      )
      .call((ax) => ax.selectAll('.tick line').attr('stroke', COLORS.axis))

  }, [data, isPending, total])

  return (
    <div className="collision-chart">

      {/* ── Header ───────────────────────────────────────────────────── */}
      <h2 className="collision-chart__heading">
        {total != null ? `${total} Collisions.` : '— Collisions.'}{' '}
        {pedCyclistPct != null ? `${pedCyclistPct}% Involved a Pedestrian or Cyclist.` : ''}
      </h2>
      <p className="collision-chart__subhead">
        Hopkins Street corridor · Sutter–Gilman bounding box · {dateRangeLabel}
        <span className="collision-chart__source"> · Source: TIMS/SWITRS</span>
      </p>

      {/* ── Secondary-source banner ───────────────────────────────────── */}
      {isPending && (
        <div className="collision-chart__pending-banner" role="status">
          <strong>Annual breakdown pending TIMS/SWITRS data.</strong>
          {' '}The figures below are from a secondary source (Bike East Bay, 2018,
          citing city staff) and have not been independently verified. Run{' '}
          <code>analysis/collisions.py</code> when TIMS data is available.
        </div>
      )}

      {/* ── Bar chart ─────────────────────────────────────────────────── */}
      {!isPending && data?.by_year && Object.keys(data.by_year).length > 0 ? (
        <div className="collision-chart__chart-container">
          <svg ref={svgRef} />
          <div className="collision-chart__legend">
            <span className="collision-chart__legend-item collision-chart__legend-item--fatal">Fatal</span>
            <span className="collision-chart__legend-item collision-chart__legend-item--severe">Severe injury</span>
            <span className="collision-chart__legend-item collision-chart__legend-item--injury">Other injury</span>
            <span className="collision-chart__legend-item collision-chart__legend-item--pdo">Property damage only</span>
          </div>
          {!hasSeverityBreakdownFlag(data) && (
            <p className="collision-chart__chart-note">
              Per-year severity breakdown not available — bars show total collisions only.
              Severity totals are shown below.
            </p>
          )}
        </div>
      ) : (
        !isPending && (
          <div className="collision-chart__chart-placeholder">
            Year-by-year chart will appear when TIMS data is available.
          </div>
        )
      )}

      {/* ── Big stats callout row ─────────────────────────────────────── */}
      <div className="collision-chart__stats">
        <div className="collision-chart__stat">
          <span className="collision-chart__stat-number">{total ?? '—'}</span>
          <span className="collision-chart__stat-label">total collisions</span>
        </div>
        <div className="collision-chart__stat">
          <span className="collision-chart__stat-number">
            {pedCyclistPct != null ? `${pedCyclistPct}%` : '—'}
          </span>
          <span className="collision-chart__stat-label">involved ped or cyclist</span>
        </div>
        <div className="collision-chart__stat">
          <span className="collision-chart__stat-number">
            {data?.by_severity?.severe_injury ?? '—'}
          </span>
          <span className="collision-chart__stat-label">severe injuries</span>
        </div>
      </div>

      {/* ── Footnote on collision figures ─────────────────────────────── */}
      <p className="collision-chart__footnote">
        Polygon covers Hopkins Street and one block north and south (Sutter to Gilman).
        Three deaths have occurred on or near this corridor: a pedestrian at Hopkins &amp; Monterey
        (2017), a cyclist on Sacramento near Hopkins (2017), and a pedestrian at California St &amp; Ada
        (January 2025, one block south). The 2017 pedestrian fatality falls just outside this
        polygon boundary; all three are documented in city staff records and the project timeline,
        and are plotted as markers on the map above.{' '}
        Multiple figures appear in public discussion: this chart covers {total ?? '—'} collisions,
        all severities, {dateRangeLabel} (TIMS/SWITRS). City workshop presentations (March 2022)
        separately document 18 injury and fatal collisions, 2016–2019, on the corridor.
      </p>

      {/* ── Source attribution ────────────────────────────────────────── */}
      <p className="collision-chart__attribution">
        {meta.attribution ?? 'Source: TIMS/SWITRS'}
      </p>

    </div>
  )
}

// Helper — checks whether by_year contains per-severity objects or plain counts
function hasSeverityBreakdownFlag(data) {
  const byYear = data?.by_year ?? {}
  const first = Object.values(byYear)[0]
  return typeof first === 'object' && first !== null
}
