/**
 * CollisionChart.jsx — Prompt 6
 *
 * "The cost of doing nothing" — collision history on the Hopkins corridor.
 *
 * DATA SOURCE:
 *   data/processed/collisions_summary.json
 *   Generated by analysis/collisions.py from TIMS/SWITRS export.
 *   Until TIMS data is available, the file is a secondary-source placeholder
 *   (_metadata.source_status === 'SECONDARY_SOURCE') and this component
 *   renders a visible DATA PENDING banner instead of the bar chart.
 *
 * Props:
 *   data         object — collision summary JSON (defaults to imported file)
 *   yearRange    [number, number] — years to bracket as "City's cited period"
 *                default: [2015, 2018]
 *
 * Attribution: "Source: TIMS/SWITRS" must be visible on every render.
 */

import { useEffect, useRef } from 'react'
import * as d3 from 'd3'
import defaultData from '@data/processed/collisions_summary.json'

// Design tokens
const COLORS = {
  fatal:          '#8b2c2c',
  injury:         '#c4713b',
  property_damage:'#8a9a78',
  grid:           'rgba(255,255,255,0.08)',
  axis:           '#8a9a78',
  text:           '#e8e4db',
  bracket:        'rgba(196,113,59,0.15)',
  bracketStroke:  'rgba(196,113,59,0.5)',
}

// Normalise severity keys from collisions_summary.json into three buckets
function normaliseSeverity(bySeverity) {
  const counts = { fatal: 0, injury: 0, property_damage: 0 }
  for (const [key, val] of Object.entries(bySeverity || {})) {
    if (key === 'fatal') {
      counts.fatal += val
    } else if (key.includes('injury') || key === 'severe_injury' || key === 'other_injury') {
      counts.injury += val
    } else {
      counts.property_damage += val
    }
  }
  return counts
}

export default function CollisionChart({ data = defaultData, yearRange = [2015, 2018] }) {
  const svgRef   = useRef(null)
  const meta     = data?._metadata ?? {}
  const isPending = meta.source_status === 'SECONDARY_SOURCE'

  // Big-stat values — come directly from JSON, never inferred
  const total        = data?.total_collisions ?? null
  const fatals       = data?.fatal_collisions ?? null
  const pedCyclistPct = data?.ped_cyclist_involvement?.pct_of_all_collisions ?? null

  // ── D3 bar chart (only when real TIMS data is available) ─────────────
  useEffect(() => {
    if (isPending) return
    if (!svgRef.current) return

    const byYear = data?.by_year ?? {}
    if (!Object.keys(byYear).length) return

    const containerWidth = svgRef.current.parentElement?.clientWidth ?? 600
    const margin = { top: 20, right: 20, bottom: 32, left: 32 }
    const width  = containerWidth - margin.left - margin.right
    const height = 180 - margin.top - margin.bottom

    // Build year-keyed stacked data
    const years = Object.keys(byYear).map(Number).sort((a, b) => a - b)

    // Severity breakdown may not be available per-year from summary JSON.
    // If by_year contains objects {fatal, injury, property_damage}, use them.
    // If by_year contains plain counts, treat entire bar as injury (conservative).
    const stack = d3.stack().keys(['property_damage', 'injury', 'fatal'])

    const rows = years.map((yr) => {
      const v = byYear[yr]
      if (typeof v === 'object' && v !== null) {
        const norm = normaliseSeverity(v)
        return { year: yr, ...norm }
      }
      // Plain count — no severity breakdown; show as injury category (most visible)
      return { year: yr, fatal: 0, injury: v, property_damage: 0 }
    })

    const series = stack(rows)

    // Clear previous render
    d3.select(svgRef.current).selectAll('*').remove()

    const svg = d3.select(svgRef.current)
      .attr('width', containerWidth)
      .attr('height', height + margin.top + margin.bottom)
      .attr('role', 'img')
      .attr('aria-label', 'Bar chart: collisions on Hopkins corridor by year')

    const g = svg.append('g')
      .attr('transform', `translate(${margin.left},${margin.top})`)

    // Scales
    const xScale = d3.scaleBand()
      .domain(years)
      .range([0, width])
      .padding(0.25)

    const yMax = d3.max(rows, (d) => d.fatal + d.injury + d.property_damage) ?? 10
    const yScale = d3.scaleLinear()
      .domain([0, Math.ceil(yMax * 1.15)])
      .range([height, 0])

    // Gridlines
    g.append('g')
      .attr('class', 'grid')
      .call(
        d3.axisLeft(yScale)
          .tickSize(-width)
          .tickFormat('')
          .ticks(4),
      )
      .call((ax) => ax.select('.domain').remove())
      .call((ax) => ax.selectAll('.tick line').attr('stroke', COLORS.grid))

    // ── "City's cited period" bracket ──────────────────────────────────
    const [y1, y2] = yearRange
    const bracketX1 = xScale(y1)
    const bracketX2 = (xScale(y2) ?? 0) + xScale.bandwidth()

    if (bracketX1 != null && bracketX2 != null) {
      g.append('rect')
        .attr('x', bracketX1)
        .attr('y', 0)
        .attr('width', bracketX2 - bracketX1)
        .attr('height', height)
        .attr('fill', COLORS.bracket)
        .attr('stroke', COLORS.bracketStroke)
        .attr('stroke-width', 1)
        .attr('rx', 2)

      g.append('text')
        .attr('x', bracketX1 + (bracketX2 - bracketX1) / 2)
        .attr('y', -6)
        .attr('text-anchor', 'middle')
        .attr('fill', '#c4713b')
        .attr('font-family', "'DM Sans', sans-serif")
        .attr('font-size', '9px')
        .attr('letter-spacing', '0.05em')
        .text("City's cited period")
    }

    // Stacked bars
    const colorScale = {
      fatal:          COLORS.fatal,
      injury:         COLORS.injury,
      property_damage:COLORS.property_damage,
    }

    g.selectAll('g.series')
      .data(series)
      .join('g')
      .attr('class', 'series')
      .attr('fill', (d) => colorScale[d.key] ?? COLORS.property_damage)
      .selectAll('rect')
      .data((d) => d)
      .join('rect')
      .attr('x', (d) => xScale(d.data.year))
      .attr('y', (d) => yScale(d[1]))
      .attr('height', (d) => yScale(d[0]) - yScale(d[1]))
      .attr('width', xScale.bandwidth())

    // X axis — years
    g.append('g')
      .attr('transform', `translate(0,${height})`)
      .call(
        d3.axisBottom(xScale)
          .tickFormat((d) => `'${String(d).slice(-2)}`)
          .tickSize(3),
      )
      .call((ax) => ax.select('.domain').attr('stroke', COLORS.axis))
      .call((ax) =>
        ax.selectAll('.tick text')
          .attr('fill', COLORS.axis)
          .attr('font-family', "'JetBrains Mono', monospace")
          .attr('font-size', '9px'),
      )
      .call((ax) =>
        ax.selectAll('.tick line').attr('stroke', COLORS.axis),
      )

    // Y axis
    g.append('g')
      .call(d3.axisLeft(yScale).ticks(4).tickSize(3))
      .call((ax) => ax.select('.domain').attr('stroke', COLORS.axis))
      .call((ax) =>
        ax.selectAll('.tick text')
          .attr('fill', COLORS.axis)
          .attr('font-family', "'JetBrains Mono', monospace")
          .attr('font-size', '9px'),
      )
      .call((ax) =>
        ax.selectAll('.tick line').attr('stroke', COLORS.axis),
      )

  }, [data, yearRange, isPending])

  return (
    <div className="collision-chart">
      {/* ── Header ───────────────────────────────────────────────────── */}
      <h2 className="collision-chart__heading">36 Collisions. Two Lives Lost.</h2>
      <p className="collision-chart__subhead">
        Hopkins Corridor · 2015–2018
        <span className="collision-chart__source">Source: TIMS/SWITRS</span>
      </p>

      {/* ── Secondary-source banner ───────────────────────────────────── */}
      {isPending && (
        <div className="collision-chart__pending-banner" role="status">
          <strong>Annual breakdown pending TIMS/SWITRS data.</strong>
          <span>
            {' '}The figures below are from a secondary source (Bike East Bay, 2018, citing
            city staff) and have not been independently verified. Run{' '}
            <code>analysis/collisions.py</code> when TIMS data is available
            to replace this file with verified data.
          </span>
        </div>
      )}

      {/* ── Bar chart — only when real data is available ─────────────── */}
      {!isPending && data?.by_year && Object.keys(data.by_year).length > 0 ? (
        <div className="collision-chart__chart-container">
          <svg ref={svgRef} />
          <div className="collision-chart__legend">
            <span className="collision-chart__legend-item collision-chart__legend-item--fatal">Fatal</span>
            <span className="collision-chart__legend-item collision-chart__legend-item--injury">Injury</span>
            <span className="collision-chart__legend-item collision-chart__legend-item--pdo">Property damage</span>
          </div>
        </div>
      ) : (
        !isPending && (
          <div className="collision-chart__chart-placeholder">
            Year-by-year chart will appear when TIMS data is available.
          </div>
        )
      )}

      {/* ── Big stats callout row ─────────────────────────────────────── */}
      <div className="collision-chart__stats">
        <div className="collision-chart__stat">
          <span className="collision-chart__stat-number">
            {total ?? '—'}
          </span>
          <span className="collision-chart__stat-label">collisions</span>
        </div>
        <div className="collision-chart__stat">
          <span className="collision-chart__stat-number">
            {pedCyclistPct != null ? `${pedCyclistPct}%` : '—'}
          </span>
          <span className="collision-chart__stat-label">involved ped or cyclist</span>
        </div>
        <div className="collision-chart__stat">
          <span className="collision-chart__stat-number">
            {fatals ?? '—'}
          </span>
          <span className="collision-chart__stat-label">fatalities</span>
        </div>
      </div>

      {/* ── Per-source attribution ────────────────────────────────────── */}
      <p className="collision-chart__attribution">
        {meta.attribution ?? 'Source: TIMS/SWITRS'}
      </p>
    </div>
  )
}
